version: '3.4'

services:
  properties:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
    ports:
      - "81:81"
      - "52964:80"

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - GRPC=false
    ports:
      - "50412:80"

  sqlserver:
    environment:
      - ACCEPT_EULA:Y
      - SA_PASSWORD:12345678a
      - MSSQL_PID:Express
    ports:
      - 1433:1433
    volumes:
      - ~/.aspnet/DBs:/var/opt/mssql

  nosqldata:
    ports:
      - "27017:27017"
    volumes:
      - ~/.aspnet/Mongo:/data/db